# For more information: https://laravel.com/docs/sail
version: '3'
services:
    html:
        image: ubuntu22-php81
        ports:
            - '80:80'
            - '3000:3000'
        volumes:
            - 'C:\Users\ks\Workspace\html:/var/www/html'
            - 'C:\Users\ks\Workspace\container\php81\apache2:/etc/apache2'
            - 'C:\Users\ks\Workspace\container\php81\log:/var/log/apache2'
        depends_on:
            - mysql
    phpmyadmin:
        image: 'phpmyadmin'
        ports:
            - '8080:80'
        environment:
            PMA_HOST: 'mysql'
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
        volumes:
            - 'C:\Users\ks\Workspace\mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
