# For more information: https://laravel.com/docs/sail
version: '3'
services:
    ubuntu22_php81:
        image: ubuntu22-php81
        ports:
            - '80:80'
            - '3000:3000'
        volumes:
            - '/var/www/docker/html:/var/www/html'
            - '/var/www/docker/container/php81/apache2:/etc/apache2'
            - '/var/www/docker/container/php81/log:/var/log/apache2'
        networks:
            - sail    
        depends_on:
            - mysql
    ubuntu20_php74:
        image: ubuntu20-php74
        ports:
            - '80:80'
            - '3000:3000'  
        volumes:
            - '/var/www/docker/html:/var/www/html'
            - '/var/www/docker/container/php74/apache2:/etc/apache2'
            - '/var/www/docker/container/php74/log:/var/log/apache2'
        networks:
            - sail
        depends_on:
            - mysql                
    phpmyadmin:
        image: 'phpmyadmin'
        ports:
            - '8080:80'
        environment:
            PMA_HOST: 'mysql'
        networks:
            - sail    
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
        networks:
            - sail    
        volumes:
            - '/var/www/docker/mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
